CREATE TABLE IF NOT EXISTS credit_notes (
  id VARCHAR(100) PRIMARY KEY,
  company_id VARCHAR(100) REFERENCES companies(id) ON DELETE CASCADE NOT NULL,
  customer_id VARCHAR(100) REFERENCES customers(id) ON DELETE CASCADE NOT NULL,
  quotation_id VARCHAR(100) REFERENCES quotations(id) ON DELETE CASCADE NOT NULL,
  amount NUMERIC(15, 2) NOT NULL,
  reason TEXT NOT NULL,
  issued_date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
